import { CategoryKey } from "./types";

interface KeywordRule {
  keywords: string[];
  category: CategoryKey;
}

const RULES: KeywordRule[] = [
  {
    keywords: [
      "restaurant",
      "food",
      "grocery",
      "groceries",
      "dinner",
      "lunch",
      "breakfast",
      "cafe",
      "coffee",
      "pizza",
      "burger",
      "sushi",
      "bakery",
      "takeout",
      "delivery",
      "mcdonald",
      "starbucks",
      "subway",
      "chipotle",
      "doordash",
      "ubereats",
      "grubhub",
      "supermarket",
      "whole foods",
      "trader joe",
      "costco",
      "walmart",
      "meal",
      "snack",
      "brunch",
    ],
    category: "food",
  },
  {
    keywords: [
      "gas",
      "fuel",
      "uber",
      "lyft",
      "taxi",
      "bus",
      "train",
      "metro",
      "subway",
      "parking",
      "toll",
      "car wash",
      "oil change",
      "tire",
      "mechanic",
      "flight",
      "airline",
      "airplane",
      "airport",
      "rental car",
      "car rental",
      "transit",
      "commute",
      "rideshare",
      "fare",
    ],
    category: "transport",
  },
  {
    keywords: [
      "amazon",
      "ebay",
      "etsy",
      "target",
      "store",
      "shop",
      "purchase",
      "clothes",
      "shoes",
      "electronics",
      "furniture",
      "home depot",
      "ikea",
      "best buy",
      "apple store",
      "online order",
      "order",
      "retail",
      "boutique",
      "mall",
    ],
    category: "shopping",
  },
  {
    keywords: [
      "movie",
      "cinema",
      "netflix",
      "spotify",
      "concert",
      "ticket",
      "game",
      "gaming",
      "steam",
      "playstation",
      "xbox",
      "nintendo",
      "theater",
      "show",
      "museum",
      "park",
      "zoo",
      "aquarium",
      "theme park",
      "disney",
      "hulu",
      "disney+",
      "hbo",
      "sport",
      "gym",
      "fitness",
      "yoga",
      "subscription",
      "streaming",
      "music",
      "book",
      "magazine",
      "hobby",
    ],
    category: "entertainment",
  },
  {
    keywords: [
      "rent",
      "mortgage",
      "electric",
      "water",
      "internet",
      "phone bill",
      "insurance",
      "utility",
      "utilities",
      "gas bill",
      "electricity",
      "heating",
      "property tax",
      "hoa",
      "cable",
      "subscription",
      "phone",
      "cell",
      "mobile plan",
    ],
    category: "bills",
  },
  {
    keywords: [
      "doctor",
      "hospital",
      "pharmacy",
      "medicine",
      "dentist",
      "therapy",
      "medical",
      "health",
      "clinic",
      "prescription",
      "drug",
      "optometrist",
      "eye",
      "vision",
      "lab",
      "vaccine",
      "vaccination",
      "copay",
      "deductible",
    ],
    category: "health",
  },
  {
    keywords: [
      "tuition",
      "school",
      "college",
      "university",
      "course",
      "class",
      "workshop",
      "seminar",
      "textbook",
      "bookstore",
      "udemy",
      "coursera",
      "khan academy",
      "tutorial",
      "learning",
      "education",
      "degree",
      "certification",
      "exam",
      "study",
      "training",
    ],
    category: "education",
  },
];

export function categorize(description: string): CategoryKey {
  const lower = description.toLowerCase();

  for (const rule of RULES) {
    for (const keyword of rule.keywords) {
      if (lower.includes(keyword)) {
        return rule.category;
      }
    }
  }

  return "other";
}
